// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrOum_QFFYLMpjOE5Xo83-S7ZnlJICct4',
    appId: '1:597912791117:web:8c51f4367b830c62d8d404',
    messagingSenderId: '597912791117',
    projectId: 'fasum-app-824e7',
    authDomain: 'fasum-app-824e7.firebaseapp.com',
    storageBucket: 'fasum-app-824e7.firebasestorage.app',
    measurementId: 'G-L0Y8947MD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeDl8JbvQrPhNzDZEC_qWvKHBylhiUrZY',
    appId: '1:597912791117:android:4e1e9fad1a15801cd8d404',
    messagingSenderId: '597912791117',
    projectId: 'fasum-app-824e7',
    storageBucket: 'fasum-app-824e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCRO9ycHzvV1LmC6Oh10tb-lEiQ6pcAG0',
    appId: '1:597912791117:ios:dab83d291e75c0dfd8d404',
    messagingSenderId: '597912791117',
    projectId: 'fasum-app-824e7',
    storageBucket: 'fasum-app-824e7.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCRO9ycHzvV1LmC6Oh10tb-lEiQ6pcAG0',
    appId: '1:597912791117:ios:dab83d291e75c0dfd8d404',
    messagingSenderId: '597912791117',
    projectId: 'fasum-app-824e7',
    storageBucket: 'fasum-app-824e7.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrOum_QFFYLMpjOE5Xo83-S7ZnlJICct4',
    appId: '1:597912791117:web:bde0107bf6ba9d7bd8d404',
    messagingSenderId: '597912791117',
    projectId: 'fasum-app-824e7',
    authDomain: 'fasum-app-824e7.firebaseapp.com',
    storageBucket: 'fasum-app-824e7.firebasestorage.app',
    measurementId: 'G-YSHYT1YTM3',
  );

}