// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEEWtRDpTwiltxUXNQN6M0SgLL-Zq402w',
    appId: '1:433864565618:web:0afc85258c4ffcbe3fb3eb',
    messagingSenderId: '433864565618',
    projectId: 'chandra-app-70373',
    authDomain: 'chandra-app-70373.firebaseapp.com',
    databaseURL: 'https://chandra-app-70373-default-rtdb.firebaseio.com',
    storageBucket: 'chandra-app-70373.firebasestorage.app',
    measurementId: 'G-3WBTNWDNEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5FpFOSzJHwBTCfp873CvH962RZzXGr0',
    appId: '1:433864565618:android:a6f930ef8ca958ac3fb3eb',
    messagingSenderId: '433864565618',
    projectId: 'chandra-app-70373',
    databaseURL: 'https://chandra-app-70373-default-rtdb.firebaseio.com',
    storageBucket: 'chandra-app-70373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQBT6iROv_9_Yws69RhZLDiiLYATlPvY8',
    appId: '1:433864565618:ios:e14a126f8139c1dd3fb3eb',
    messagingSenderId: '433864565618',
    projectId: 'chandra-app-70373',
    databaseURL: 'https://chandra-app-70373-default-rtdb.firebaseio.com',
    storageBucket: 'chandra-app-70373.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQBT6iROv_9_Yws69RhZLDiiLYATlPvY8',
    appId: '1:433864565618:ios:e14a126f8139c1dd3fb3eb',
    messagingSenderId: '433864565618',
    projectId: 'chandra-app-70373',
    databaseURL: 'https://chandra-app-70373-default-rtdb.firebaseio.com',
    storageBucket: 'chandra-app-70373.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEEWtRDpTwiltxUXNQN6M0SgLL-Zq402w',
    appId: '1:433864565618:web:1ce8258635dfca923fb3eb',
    messagingSenderId: '433864565618',
    projectId: 'chandra-app-70373',
    authDomain: 'chandra-app-70373.firebaseapp.com',
    databaseURL: 'https://chandra-app-70373-default-rtdb.firebaseio.com',
    storageBucket: 'chandra-app-70373.firebasestorage.app',
    measurementId: 'G-NGGVC5GSFB',
  );
}
